version: '3'
services:
  transmission:
    restart: unless-stopped
    image: jsiu/transmission
    container_name: transmission
    logging:
      options:
        tag: "{{.Name}}"
    network_mode: host
    volumes:
      - ${TRANSMISSION_CNF}:/transmission/.config/transmission-daemon:rw
    environment:
      - P_TZ=${TZ}
      - PUID=${TRANSMISSION_UID}
      - PGID=${TRANSMISSION_GID}
      # Transmission Web Control (true/false)
      - PTWC=${TRANSMISSION_TWC}